# Generated by Django 5.2.1 on 2025-05-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='device_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
